#ifndef _ALTERA_CPU_INST_H_
#define _ALTERA_CPU_INST_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'dut_dut_e0_if0_p0_s0' in
 * file './soc_system/simulation/submodules/hps.sopcinfo'.
 */

/*
 * This file contains macros for module 'cpu_inst' and devices
 * connected to the following masters:
 *   data_master
 *   instruction_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for module 'cpu_inst', class 'altera_nios2_qsys'.
 * The macros have no prefix.
 */
#define BIG_ENDIAN 0
#define BREAK_ADDR 0x20
#define CPU_FREQ 50000000
#define CPU_ID_SIZE 1
#define CPU_ID_VALUE 0x00000000
#define CPU_IMPLEMENTATION "tiny"
#define DATA_ADDR_WIDTH 19
#define DCACHE_LINE_SIZE 0
#define DCACHE_LINE_SIZE_LOG2 0
#define DCACHE_SIZE 0
#define EXCEPTION_ADDR 0x10020
#define FLUSHDA_SUPPORTED 
#define HARDWARE_DIVIDE_PRESENT 0
#define HARDWARE_MULTIPLY_PRESENT 0
#define HARDWARE_MULX_PRESENT 0
#define HAS_DEBUG_CORE 1
#define HAS_DEBUG_STUB 
#define HAS_JMPI_INSTRUCTION 
#define ICACHE_LINE_SIZE 0
#define ICACHE_LINE_SIZE_LOG2 0
#define ICACHE_SIZE 0
#define INITDA_SUPPORTED 
#define INST_ADDR_WIDTH 17
#define NUM_OF_SHADOW_REG_SETS 0
#define RESET_ADDR 0x10000

/*
 * Macros for device 'sequencer_mem', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'SEQUENCER_MEM_'.
 * The prefix is the slave descriptor.
 */
#define SEQUENCER_MEM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define SEQUENCER_MEM_COMPONENT_NAME sequencer_mem
#define SEQUENCER_MEM_BASE 0x10000
#define SEQUENCER_MEM_SPAN 65536
#define SEQUENCER_MEM_END 0x1ffff
#define SEQUENCER_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SEQUENCER_MEM_INIT_CONTENTS_FILE "sequencer_mem"
#define SEQUENCER_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SEQUENCER_MEM_GUI_RAM_BLOCK_TYPE "Automatic"
#define SEQUENCER_MEM_WRITABLE 1
#define SEQUENCER_MEM_DUAL_PORT 1
#define SEQUENCER_MEM_SINGLE_CLOCK_OP 0
#define SEQUENCER_MEM_SIZE_VALUE 65536
#define SEQUENCER_MEM_SIZE_MULTIPLE 1
#define SEQUENCER_MEM_CONTENTS_INFO ""
#define SEQUENCER_MEM_RAM_BLOCK_TYPE "Auto"
#define SEQUENCER_MEM_INIT_MEM_CONTENT 0
#define SEQUENCER_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SEQUENCER_MEM_INSTANCE_ID "NONE"
#define SEQUENCER_MEM_READ_DURING_WRITE_MODE "DONT_CARE"
#define SEQUENCER_MEM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define SEQUENCER_MEM_MEMORY_INFO_HAS_BYTE_LANE 0
#define SEQUENCER_MEM_MEMORY_INFO_GENERATE_HEX 1
#define SEQUENCER_MEM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define SEQUENCER_MEM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define SEQUENCER_MEM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define SEQUENCER_MEM_MEMORY_INFO_MEM_INIT_FILENAME dut_dut_e0_if0_p0_s0_sequencer_mem

/*
 * Macros for device 'sequencer_ptr_mgr_inst', class 'sequencer_ptr_mgr_100'
 * The macros are prefixed with 'SEQUENCER_PTR_MGR_INST_'.
 * The prefix is the slave descriptor.
 */
#define SEQUENCER_PTR_MGR_INST_COMPONENT_TYPE sequencer_ptr_mgr_100
#define SEQUENCER_PTR_MGR_INST_COMPONENT_NAME sequencer_ptr_mgr_inst
#define SEQUENCER_PTR_MGR_INST_BASE 0x40000
#define SEQUENCER_PTR_MGR_INST_SPAN 32768
#define SEQUENCER_PTR_MGR_INST_END 0x47fff

/*
 * Macros for device 'sequencer_phy_mgr_inst', class 'sequencer_phy_mgr_100'
 * The macros are prefixed with 'SEQUENCER_PHY_MGR_INST_'.
 * The prefix is the slave descriptor.
 */
#define SEQUENCER_PHY_MGR_INST_COMPONENT_TYPE sequencer_phy_mgr_100
#define SEQUENCER_PHY_MGR_INST_COMPONENT_NAME sequencer_phy_mgr_inst
#define SEQUENCER_PHY_MGR_INST_BASE 0x48000
#define SEQUENCER_PHY_MGR_INST_SPAN 32768
#define SEQUENCER_PHY_MGR_INST_END 0x4ffff

/*
 * Macros for device 'sequencer_rw_mgr_inst', class 'sequencer_rw_mgr_ddr2_110'
 * The macros are prefixed with 'SEQUENCER_RW_MGR_INST_'.
 * The prefix is the slave descriptor.
 */
#define SEQUENCER_RW_MGR_INST_COMPONENT_TYPE sequencer_rw_mgr_ddr2_110
#define SEQUENCER_RW_MGR_INST_COMPONENT_NAME sequencer_rw_mgr_inst
#define SEQUENCER_RW_MGR_INST_BASE 0x50000
#define SEQUENCER_RW_MGR_INST_SPAN 32768
#define SEQUENCER_RW_MGR_INST_END 0x57fff

/*
 * Macros for device 'sequencer_scc_mgr_inst', class 'sequencer_scc_mgr_110'
 * The macros are prefixed with 'SEQUENCER_SCC_MGR_INST_'.
 * The prefix is the slave descriptor.
 */
#define SEQUENCER_SCC_MGR_INST_COMPONENT_TYPE sequencer_scc_mgr_110
#define SEQUENCER_SCC_MGR_INST_COMPONENT_NAME sequencer_scc_mgr_inst
#define SEQUENCER_SCC_MGR_INST_BASE 0x58000
#define SEQUENCER_SCC_MGR_INST_SPAN 32768
#define SEQUENCER_SCC_MGR_INST_END 0x5ffff

/*
 * Macros for device 'sequencer_data_mgr_inst', class 'sequencer_data_mgr_110'
 * The macros are prefixed with 'SEQUENCER_DATA_MGR_INST_'.
 * The prefix is the slave descriptor.
 */
#define SEQUENCER_DATA_MGR_INST_COMPONENT_TYPE sequencer_data_mgr_110
#define SEQUENCER_DATA_MGR_INST_COMPONENT_NAME sequencer_data_mgr_inst
#define SEQUENCER_DATA_MGR_INST_BASE 0x60000
#define SEQUENCER_DATA_MGR_INST_SPAN 32768
#define SEQUENCER_DATA_MGR_INST_END 0x67fff

/*
 * Macros for device 'sequencer_reg_file_inst', class 'sequencer_reg_file_111'
 * The macros are prefixed with 'SEQUENCER_REG_FILE_INST_'.
 * The prefix is the slave descriptor.
 */
#define SEQUENCER_REG_FILE_INST_COMPONENT_TYPE sequencer_reg_file_111
#define SEQUENCER_REG_FILE_INST_COMPONENT_NAME sequencer_reg_file_inst
#define SEQUENCER_REG_FILE_INST_BASE 0x70000
#define SEQUENCER_REG_FILE_INST_SPAN 32768
#define SEQUENCER_REG_FILE_INST_END 0x77fff

/*
 * Macros for device 'sequencer_timer_inst', class 'sequencer_timer_120'
 * The macros are prefixed with 'SEQUENCER_TIMER_INST_'.
 * The prefix is the slave descriptor.
 */
#define SEQUENCER_TIMER_INST_COMPONENT_TYPE sequencer_timer_120
#define SEQUENCER_TIMER_INST_COMPONENT_NAME sequencer_timer_inst
#define SEQUENCER_TIMER_INST_BASE 0x79ff0
#define SEQUENCER_TIMER_INST_SPAN 24592
#define SEQUENCER_TIMER_INST_END 0x7ffff


#endif /* _ALTERA_CPU_INST_H_ */
