#ifndef _ALTERA_DUT_DUT_E0_IF0_P0_S0_H_
#define _ALTERA_DUT_DUT_E0_IF0_P0_S0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'dut_dut_e0_if0_p0_s0' in
 * file './soc_system/simulation/submodules/hps.sopcinfo'.
 */

/*
 * This file contains macros for all modules with masters in the system and
 * all the devices connected to those masters.
 * Macro names have unique prefixes to prevent duplicate names.
 */

/*
 * Macros for module 'cpu_inst', class 'altera_nios2_qsys'.
 * The macros are prefixed with 'CPU_INST_'.
 * The prefix comes from the module name.
 */
#define CPU_INST_COMPONENT_TYPE altera_nios2_qsys
#define CPU_INST_COMPONENT_NAME cpu_inst
#define CPU_INST_BIG_ENDIAN 0
#define CPU_INST_BREAK_ADDR 0x20
#define CPU_INST_CPU_FREQ 50000000
#define CPU_INST_CPU_ID_SIZE 1
#define CPU_INST_CPU_ID_VALUE 0x00000000
#define CPU_INST_CPU_IMPLEMENTATION "tiny"
#define CPU_INST_DATA_ADDR_WIDTH 19
#define CPU_INST_DCACHE_LINE_SIZE 0
#define CPU_INST_DCACHE_LINE_SIZE_LOG2 0
#define CPU_INST_DCACHE_SIZE 0
#define CPU_INST_EXCEPTION_ADDR 0x10020
#define CPU_INST_FLUSHDA_SUPPORTED 
#define CPU_INST_HARDWARE_DIVIDE_PRESENT 0
#define CPU_INST_HARDWARE_MULTIPLY_PRESENT 0
#define CPU_INST_HARDWARE_MULX_PRESENT 0
#define CPU_INST_HAS_DEBUG_CORE 1
#define CPU_INST_HAS_DEBUG_STUB 
#define CPU_INST_HAS_JMPI_INSTRUCTION 
#define CPU_INST_ICACHE_LINE_SIZE 0
#define CPU_INST_ICACHE_LINE_SIZE_LOG2 0
#define CPU_INST_ICACHE_SIZE 0
#define CPU_INST_INITDA_SUPPORTED 
#define CPU_INST_INST_ADDR_WIDTH 17
#define CPU_INST_NUM_OF_SHADOW_REG_SETS 0
#define CPU_INST_RESET_ADDR 0x10000

/*
 * Macros for device 'sequencer_mem', class 'altera_avalon_onchip_memory2'
 * Path to the device is from the master group 'cpu_inst'.
 * The macros are prefixed with 'CPU_INST_SEQUENCER_MEM_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define CPU_INST_SEQUENCER_MEM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define CPU_INST_SEQUENCER_MEM_COMPONENT_NAME sequencer_mem
#define CPU_INST_SEQUENCER_MEM_BASE 0x10000
#define CPU_INST_SEQUENCER_MEM_SPAN 65536
#define CPU_INST_SEQUENCER_MEM_END 0x1ffff
#define CPU_INST_SEQUENCER_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define CPU_INST_SEQUENCER_MEM_INIT_CONTENTS_FILE "sequencer_mem"
#define CPU_INST_SEQUENCER_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define CPU_INST_SEQUENCER_MEM_GUI_RAM_BLOCK_TYPE "Automatic"
#define CPU_INST_SEQUENCER_MEM_WRITABLE 1
#define CPU_INST_SEQUENCER_MEM_DUAL_PORT 1
#define CPU_INST_SEQUENCER_MEM_SINGLE_CLOCK_OP 0
#define CPU_INST_SEQUENCER_MEM_SIZE_VALUE 65536
#define CPU_INST_SEQUENCER_MEM_SIZE_MULTIPLE 1
#define CPU_INST_SEQUENCER_MEM_CONTENTS_INFO ""
#define CPU_INST_SEQUENCER_MEM_RAM_BLOCK_TYPE "Auto"
#define CPU_INST_SEQUENCER_MEM_INIT_MEM_CONTENT 0
#define CPU_INST_SEQUENCER_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define CPU_INST_SEQUENCER_MEM_INSTANCE_ID "NONE"
#define CPU_INST_SEQUENCER_MEM_READ_DURING_WRITE_MODE "DONT_CARE"
#define CPU_INST_SEQUENCER_MEM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define CPU_INST_SEQUENCER_MEM_MEMORY_INFO_HAS_BYTE_LANE 0
#define CPU_INST_SEQUENCER_MEM_MEMORY_INFO_GENERATE_HEX 1
#define CPU_INST_SEQUENCER_MEM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define CPU_INST_SEQUENCER_MEM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define CPU_INST_SEQUENCER_MEM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define CPU_INST_SEQUENCER_MEM_MEMORY_INFO_MEM_INIT_FILENAME dut_dut_e0_if0_p0_s0_sequencer_mem

/*
 * Macros for device 'sequencer_ptr_mgr_inst', class 'sequencer_ptr_mgr_100'
 * Path to the device is from the master group 'cpu_inst'.
 * The macros are prefixed with 'CPU_INST_SEQUENCER_PTR_MGR_INST_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define CPU_INST_SEQUENCER_PTR_MGR_INST_COMPONENT_TYPE sequencer_ptr_mgr_100
#define CPU_INST_SEQUENCER_PTR_MGR_INST_COMPONENT_NAME sequencer_ptr_mgr_inst
#define CPU_INST_SEQUENCER_PTR_MGR_INST_BASE 0x40000
#define CPU_INST_SEQUENCER_PTR_MGR_INST_SPAN 32768
#define CPU_INST_SEQUENCER_PTR_MGR_INST_END 0x47fff

/*
 * Macros for device 'sequencer_phy_mgr_inst', class 'sequencer_phy_mgr_100'
 * Path to the device is from the master group 'cpu_inst'.
 * The macros are prefixed with 'CPU_INST_SEQUENCER_PHY_MGR_INST_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define CPU_INST_SEQUENCER_PHY_MGR_INST_COMPONENT_TYPE sequencer_phy_mgr_100
#define CPU_INST_SEQUENCER_PHY_MGR_INST_COMPONENT_NAME sequencer_phy_mgr_inst
#define CPU_INST_SEQUENCER_PHY_MGR_INST_BASE 0x48000
#define CPU_INST_SEQUENCER_PHY_MGR_INST_SPAN 32768
#define CPU_INST_SEQUENCER_PHY_MGR_INST_END 0x4ffff

/*
 * Macros for device 'sequencer_rw_mgr_inst', class 'sequencer_rw_mgr_ddr2_110'
 * Path to the device is from the master group 'cpu_inst'.
 * The macros are prefixed with 'CPU_INST_SEQUENCER_RW_MGR_INST_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define CPU_INST_SEQUENCER_RW_MGR_INST_COMPONENT_TYPE sequencer_rw_mgr_ddr2_110
#define CPU_INST_SEQUENCER_RW_MGR_INST_COMPONENT_NAME sequencer_rw_mgr_inst
#define CPU_INST_SEQUENCER_RW_MGR_INST_BASE 0x50000
#define CPU_INST_SEQUENCER_RW_MGR_INST_SPAN 32768
#define CPU_INST_SEQUENCER_RW_MGR_INST_END 0x57fff

/*
 * Macros for device 'sequencer_scc_mgr_inst', class 'sequencer_scc_mgr_110'
 * Path to the device is from the master group 'cpu_inst'.
 * The macros are prefixed with 'CPU_INST_SEQUENCER_SCC_MGR_INST_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define CPU_INST_SEQUENCER_SCC_MGR_INST_COMPONENT_TYPE sequencer_scc_mgr_110
#define CPU_INST_SEQUENCER_SCC_MGR_INST_COMPONENT_NAME sequencer_scc_mgr_inst
#define CPU_INST_SEQUENCER_SCC_MGR_INST_BASE 0x58000
#define CPU_INST_SEQUENCER_SCC_MGR_INST_SPAN 32768
#define CPU_INST_SEQUENCER_SCC_MGR_INST_END 0x5ffff

/*
 * Macros for device 'sequencer_data_mgr_inst', class 'sequencer_data_mgr_110'
 * Path to the device is from the master group 'cpu_inst'.
 * The macros are prefixed with 'CPU_INST_SEQUENCER_DATA_MGR_INST_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define CPU_INST_SEQUENCER_DATA_MGR_INST_COMPONENT_TYPE sequencer_data_mgr_110
#define CPU_INST_SEQUENCER_DATA_MGR_INST_COMPONENT_NAME sequencer_data_mgr_inst
#define CPU_INST_SEQUENCER_DATA_MGR_INST_BASE 0x60000
#define CPU_INST_SEQUENCER_DATA_MGR_INST_SPAN 32768
#define CPU_INST_SEQUENCER_DATA_MGR_INST_END 0x67fff

/*
 * Macros for device 'sequencer_reg_file_inst', class 'sequencer_reg_file_111'
 * Path to the device is from the master group 'cpu_inst'.
 * The macros are prefixed with 'CPU_INST_SEQUENCER_REG_FILE_INST_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define CPU_INST_SEQUENCER_REG_FILE_INST_COMPONENT_TYPE sequencer_reg_file_111
#define CPU_INST_SEQUENCER_REG_FILE_INST_COMPONENT_NAME sequencer_reg_file_inst
#define CPU_INST_SEQUENCER_REG_FILE_INST_BASE 0x70000
#define CPU_INST_SEQUENCER_REG_FILE_INST_SPAN 32768
#define CPU_INST_SEQUENCER_REG_FILE_INST_END 0x77fff

/*
 * Macros for device 'sequencer_timer_inst', class 'sequencer_timer_120'
 * Path to the device is from the master group 'cpu_inst'.
 * The macros are prefixed with 'CPU_INST_SEQUENCER_TIMER_INST_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define CPU_INST_SEQUENCER_TIMER_INST_COMPONENT_TYPE sequencer_timer_120
#define CPU_INST_SEQUENCER_TIMER_INST_COMPONENT_NAME sequencer_timer_inst
#define CPU_INST_SEQUENCER_TIMER_INST_BASE 0x79ff0
#define CPU_INST_SEQUENCER_TIMER_INST_SPAN 24592
#define CPU_INST_SEQUENCER_TIMER_INST_END 0x7ffff

/*
 * Macros for device 'sequencer_mem', class 'altera_avalon_onchip_memory2'
 * Path to the device is from the master group 'sequencer_mem_bridge_inst'.
 * The macros are prefixed with 'SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_COMPONENT_NAME sequencer_mem
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_BASE 0x0
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_SPAN 65536
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_END 0xffff
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_INIT_CONTENTS_FILE "sequencer_mem"
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_GUI_RAM_BLOCK_TYPE "Automatic"
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_WRITABLE 1
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_DUAL_PORT 1
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_SINGLE_CLOCK_OP 0
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_SIZE_VALUE 65536
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_SIZE_MULTIPLE 1
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_CONTENTS_INFO ""
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_RAM_BLOCK_TYPE "Auto"
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_INIT_MEM_CONTENT 0
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_INSTANCE_ID "NONE"
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_READ_DURING_WRITE_MODE "DONT_CARE"
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_MEMORY_INFO_HAS_BYTE_LANE 0
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_MEMORY_INFO_GENERATE_HEX 1
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define SEQUENCER_MEM_BRIDGE_INST_SEQUENCER_MEM_MEMORY_INFO_MEM_INIT_FILENAME dut_dut_e0_if0_p0_s0_sequencer_mem

/*
 * Macros for device 'sequencer_mem', class 'altera_avalon_onchip_memory2'
 * Path to the device is from the master group 'dmaster'.
 * The macros are prefixed with 'DMASTER_SEQUENCER_MEM_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMASTER_SEQUENCER_MEM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define DMASTER_SEQUENCER_MEM_COMPONENT_NAME sequencer_mem
#define DMASTER_SEQUENCER_MEM_BASE 0x20000
#define DMASTER_SEQUENCER_MEM_SPAN 65536
#define DMASTER_SEQUENCER_MEM_END 0x2ffff
#define DMASTER_SEQUENCER_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define DMASTER_SEQUENCER_MEM_INIT_CONTENTS_FILE "sequencer_mem"
#define DMASTER_SEQUENCER_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define DMASTER_SEQUENCER_MEM_GUI_RAM_BLOCK_TYPE "Automatic"
#define DMASTER_SEQUENCER_MEM_WRITABLE 1
#define DMASTER_SEQUENCER_MEM_DUAL_PORT 1
#define DMASTER_SEQUENCER_MEM_SINGLE_CLOCK_OP 0
#define DMASTER_SEQUENCER_MEM_SIZE_VALUE 65536
#define DMASTER_SEQUENCER_MEM_SIZE_MULTIPLE 1
#define DMASTER_SEQUENCER_MEM_CONTENTS_INFO ""
#define DMASTER_SEQUENCER_MEM_RAM_BLOCK_TYPE "Auto"
#define DMASTER_SEQUENCER_MEM_INIT_MEM_CONTENT 0
#define DMASTER_SEQUENCER_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define DMASTER_SEQUENCER_MEM_INSTANCE_ID "NONE"
#define DMASTER_SEQUENCER_MEM_READ_DURING_WRITE_MODE "DONT_CARE"
#define DMASTER_SEQUENCER_MEM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define DMASTER_SEQUENCER_MEM_MEMORY_INFO_HAS_BYTE_LANE 0
#define DMASTER_SEQUENCER_MEM_MEMORY_INFO_GENERATE_HEX 1
#define DMASTER_SEQUENCER_MEM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define DMASTER_SEQUENCER_MEM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define DMASTER_SEQUENCER_MEM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define DMASTER_SEQUENCER_MEM_MEMORY_INFO_MEM_INIT_FILENAME dut_dut_e0_if0_p0_s0_sequencer_mem

/*
 * Macros for device 'sequencer_reg_file_inst', class 'sequencer_reg_file_111'
 * Path to the device is from the master group 'dmaster'.
 * The macros are prefixed with 'DMASTER_SEQUENCER_REG_FILE_INST_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMASTER_SEQUENCER_REG_FILE_INST_COMPONENT_TYPE sequencer_reg_file_111
#define DMASTER_SEQUENCER_REG_FILE_INST_COMPONENT_NAME sequencer_reg_file_inst
#define DMASTER_SEQUENCER_REG_FILE_INST_BASE 0x70000
#define DMASTER_SEQUENCER_REG_FILE_INST_SPAN 32768
#define DMASTER_SEQUENCER_REG_FILE_INST_END 0x77fff

/*
 * Macros for device 'sequencer_timer_inst', class 'sequencer_timer_120'
 * Path to the device is from the master group 'dmaster'.
 * The macros are prefixed with 'DMASTER_SEQUENCER_TIMER_INST_'.
 * The prefix is the master group descriptor and the slave descriptor.
 */
#define DMASTER_SEQUENCER_TIMER_INST_COMPONENT_TYPE sequencer_timer_120
#define DMASTER_SEQUENCER_TIMER_INST_COMPONENT_NAME sequencer_timer_inst
#define DMASTER_SEQUENCER_TIMER_INST_BASE 0x79ff0
#define DMASTER_SEQUENCER_TIMER_INST_SPAN 24592
#define DMASTER_SEQUENCER_TIMER_INST_END 0x7ffff


#endif /* _ALTERA_DUT_DUT_E0_IF0_P0_S0_H_ */
