#ifndef _ALTERA_MM_BRIDGE_0_H_
#define _ALTERA_MM_BRIDGE_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file 'soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'mm_bridge_0' and devices
 * connected to the following master:
 *   m0
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'ILC', class 'interrupt_latency_counter'
 * The macros are prefixed with 'ILC_'.
 * The prefix is the slave descriptor.
 */
#define ILC_COMPONENT_TYPE interrupt_latency_counter
#define ILC_COMPONENT_NAME ILC
#define ILC_BASE 0x0
#define ILC_SPAN 256
#define ILC_END 0xff

/*
 * Macros for device 'hex5_hex4', class 'altera_avalon_pio'
 * The macros are prefixed with 'HEX5_HEX4_'.
 * The prefix is the slave descriptor.
 */
#define HEX5_HEX4_COMPONENT_TYPE altera_avalon_pio
#define HEX5_HEX4_COMPONENT_NAME hex5_hex4
#define HEX5_HEX4_BASE 0x100
#define HEX5_HEX4_SPAN 16
#define HEX5_HEX4_END 0x10f
#define HEX5_HEX4_BIT_CLEARING_EDGE_REGISTER 0
#define HEX5_HEX4_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEX5_HEX4_CAPTURE 0
#define HEX5_HEX4_DATA_WIDTH 16
#define HEX5_HEX4_DO_TEST_BENCH_WIRING 0
#define HEX5_HEX4_DRIVEN_SIM_VALUE 0
#define HEX5_HEX4_EDGE_TYPE NONE
#define HEX5_HEX4_FREQ 50000000
#define HEX5_HEX4_HAS_IN 0
#define HEX5_HEX4_HAS_OUT 1
#define HEX5_HEX4_HAS_TRI 0
#define HEX5_HEX4_IRQ_TYPE NONE
#define HEX5_HEX4_RESET_VALUE 0

/*
 * Macros for device 'hex3_hex0', class 'altera_avalon_pio'
 * The macros are prefixed with 'HEX3_HEX0_'.
 * The prefix is the slave descriptor.
 */
#define HEX3_HEX0_COMPONENT_TYPE altera_avalon_pio
#define HEX3_HEX0_COMPONENT_NAME hex3_hex0
#define HEX3_HEX0_BASE 0x110
#define HEX3_HEX0_SPAN 16
#define HEX3_HEX0_END 0x11f
#define HEX3_HEX0_BIT_CLEARING_EDGE_REGISTER 0
#define HEX3_HEX0_BIT_MODIFYING_OUTPUT_REGISTER 0
#define HEX3_HEX0_CAPTURE 0
#define HEX3_HEX0_DATA_WIDTH 32
#define HEX3_HEX0_DO_TEST_BENCH_WIRING 0
#define HEX3_HEX0_DRIVEN_SIM_VALUE 0
#define HEX3_HEX0_EDGE_TYPE NONE
#define HEX3_HEX0_FREQ 50000000
#define HEX3_HEX0_HAS_IN 0
#define HEX3_HEX0_HAS_OUT 1
#define HEX3_HEX0_HAS_TRI 0
#define HEX3_HEX0_IRQ_TYPE NONE
#define HEX3_HEX0_RESET_VALUE 0

/*
 * Macros for device 'led_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'LED_PIO_'.
 * The prefix is the slave descriptor.
 */
#define LED_PIO_COMPONENT_TYPE altera_avalon_pio
#define LED_PIO_COMPONENT_NAME led_pio
#define LED_PIO_BASE 0x120
#define LED_PIO_SPAN 16
#define LED_PIO_END 0x12f
#define LED_PIO_BIT_CLEARING_EDGE_REGISTER 0
#define LED_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define LED_PIO_CAPTURE 0
#define LED_PIO_DATA_WIDTH 10
#define LED_PIO_DO_TEST_BENCH_WIRING 0
#define LED_PIO_DRIVEN_SIM_VALUE 0
#define LED_PIO_EDGE_TYPE NONE
#define LED_PIO_FREQ 50000000
#define LED_PIO_HAS_IN 0
#define LED_PIO_HAS_OUT 1
#define LED_PIO_HAS_TRI 0
#define LED_PIO_IRQ_TYPE NONE
#define LED_PIO_RESET_VALUE 0

/*
 * Macros for device 'dipsw_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'DIPSW_PIO_'.
 * The prefix is the slave descriptor.
 */
#define DIPSW_PIO_COMPONENT_TYPE altera_avalon_pio
#define DIPSW_PIO_COMPONENT_NAME dipsw_pio
#define DIPSW_PIO_BASE 0x130
#define DIPSW_PIO_SPAN 16
#define DIPSW_PIO_END 0x13f
#define DIPSW_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define DIPSW_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DIPSW_PIO_CAPTURE 1
#define DIPSW_PIO_DATA_WIDTH 10
#define DIPSW_PIO_DO_TEST_BENCH_WIRING 0
#define DIPSW_PIO_DRIVEN_SIM_VALUE 0
#define DIPSW_PIO_EDGE_TYPE ANY
#define DIPSW_PIO_FREQ 50000000
#define DIPSW_PIO_HAS_IN 1
#define DIPSW_PIO_HAS_OUT 0
#define DIPSW_PIO_HAS_TRI 0
#define DIPSW_PIO_IRQ_TYPE EDGE
#define DIPSW_PIO_RESET_VALUE 0

/*
 * Macros for device 'button_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_PIO_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_PIO_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_PIO_COMPONENT_NAME button_pio
#define BUTTON_PIO_BASE 0x140
#define BUTTON_PIO_SPAN 16
#define BUTTON_PIO_END 0x14f
#define BUTTON_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define BUTTON_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_PIO_CAPTURE 1
#define BUTTON_PIO_DATA_WIDTH 4
#define BUTTON_PIO_DO_TEST_BENCH_WIRING 0
#define BUTTON_PIO_DRIVEN_SIM_VALUE 0
#define BUTTON_PIO_EDGE_TYPE FALLING
#define BUTTON_PIO_FREQ 50000000
#define BUTTON_PIO_HAS_IN 1
#define BUTTON_PIO_HAS_OUT 0
#define BUTTON_PIO_HAS_TRI 0
#define BUTTON_PIO_IRQ_TYPE EDGE
#define BUTTON_PIO_RESET_VALUE 0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x150
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x157
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1779739681

/*
 * Macros for device 'pio_magnitude', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_MAGNITUDE_'.
 * The prefix is the slave descriptor.
 */
#define PIO_MAGNITUDE_COMPONENT_TYPE altera_avalon_pio
#define PIO_MAGNITUDE_COMPONENT_NAME pio_magnitude
#define PIO_MAGNITUDE_BASE 0x300
#define PIO_MAGNITUDE_SPAN 16
#define PIO_MAGNITUDE_END 0x30f
#define PIO_MAGNITUDE_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_MAGNITUDE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_MAGNITUDE_CAPTURE 0
#define PIO_MAGNITUDE_DATA_WIDTH 32
#define PIO_MAGNITUDE_DO_TEST_BENCH_WIRING 0
#define PIO_MAGNITUDE_DRIVEN_SIM_VALUE 0
#define PIO_MAGNITUDE_EDGE_TYPE NONE
#define PIO_MAGNITUDE_FREQ 50000000
#define PIO_MAGNITUDE_HAS_IN 1
#define PIO_MAGNITUDE_HAS_OUT 0
#define PIO_MAGNITUDE_HAS_TRI 0
#define PIO_MAGNITUDE_IRQ_TYPE NONE
#define PIO_MAGNITUDE_RESET_VALUE 0

/*
 * Macros for device 'pio_fase', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_FASE_'.
 * The prefix is the slave descriptor.
 */
#define PIO_FASE_COMPONENT_TYPE altera_avalon_pio
#define PIO_FASE_COMPONENT_NAME pio_fase
#define PIO_FASE_BASE 0x310
#define PIO_FASE_SPAN 16
#define PIO_FASE_END 0x31f
#define PIO_FASE_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_FASE_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_FASE_CAPTURE 0
#define PIO_FASE_DATA_WIDTH 32
#define PIO_FASE_DO_TEST_BENCH_WIRING 0
#define PIO_FASE_DRIVEN_SIM_VALUE 0
#define PIO_FASE_EDGE_TYPE NONE
#define PIO_FASE_FREQ 50000000
#define PIO_FASE_HAS_IN 1
#define PIO_FASE_HAS_OUT 0
#define PIO_FASE_HAS_TRI 0
#define PIO_FASE_IRQ_TYPE NONE
#define PIO_FASE_RESET_VALUE 0

/*
 * Macros for device 'pio_Freq', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_FREQ_'.
 * The prefix is the slave descriptor.
 */
#define PIO_FREQ_COMPONENT_TYPE altera_avalon_pio
#define PIO_FREQ_COMPONENT_NAME pio_Freq
#define PIO_FREQ_BASE 0x320
#define PIO_FREQ_SPAN 16
#define PIO_FREQ_END 0x32f
#define PIO_FREQ_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_FREQ_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_FREQ_CAPTURE 0
#define PIO_FREQ_DATA_WIDTH 32
#define PIO_FREQ_DO_TEST_BENCH_WIRING 0
#define PIO_FREQ_DRIVEN_SIM_VALUE 0
#define PIO_FREQ_EDGE_TYPE NONE
#define PIO_FREQ_FREQ 50000000
#define PIO_FREQ_HAS_IN 1
#define PIO_FREQ_HAS_OUT 0
#define PIO_FREQ_HAS_TRI 0
#define PIO_FREQ_IRQ_TYPE NONE
#define PIO_FREQ_RESET_VALUE 0

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


#endif /* _ALTERA_MM_BRIDGE_0_H_ */
