#ifndef _ALTERA_SEQUENCER_MEM_BRIDGE_INST_H_
#define _ALTERA_SEQUENCER_MEM_BRIDGE_INST_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'dut_dut_e0_if0_p0_s0' in
 * file './soc_system/simulation/submodules/hps.sopcinfo'.
 */

/*
 * This file contains macros for module 'sequencer_mem_bridge_inst' and devices
 * connected to the following master:
 *   avalon_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'sequencer_mem', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'SEQUENCER_MEM_'.
 * The prefix is the slave descriptor.
 */
#define SEQUENCER_MEM_COMPONENT_TYPE altera_avalon_onchip_memory2
#define SEQUENCER_MEM_COMPONENT_NAME sequencer_mem
#define SEQUENCER_MEM_BASE 0x0
#define SEQUENCER_MEM_SPAN 65536
#define SEQUENCER_MEM_END 0xffff
#define SEQUENCER_MEM_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SEQUENCER_MEM_INIT_CONTENTS_FILE "sequencer_mem"
#define SEQUENCER_MEM_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SEQUENCER_MEM_GUI_RAM_BLOCK_TYPE "Automatic"
#define SEQUENCER_MEM_WRITABLE 1
#define SEQUENCER_MEM_DUAL_PORT 1
#define SEQUENCER_MEM_SINGLE_CLOCK_OP 0
#define SEQUENCER_MEM_SIZE_VALUE 65536
#define SEQUENCER_MEM_SIZE_MULTIPLE 1
#define SEQUENCER_MEM_CONTENTS_INFO ""
#define SEQUENCER_MEM_RAM_BLOCK_TYPE "Auto"
#define SEQUENCER_MEM_INIT_MEM_CONTENT 0
#define SEQUENCER_MEM_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SEQUENCER_MEM_INSTANCE_ID "NONE"
#define SEQUENCER_MEM_READ_DURING_WRITE_MODE "DONT_CARE"
#define SEQUENCER_MEM_MEMORY_INFO_MEM_INIT_DATA_WIDTH 32
#define SEQUENCER_MEM_MEMORY_INFO_HAS_BYTE_LANE 0
#define SEQUENCER_MEM_MEMORY_INFO_GENERATE_HEX 1
#define SEQUENCER_MEM_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define SEQUENCER_MEM_MEMORY_INFO_GENERATE_DAT_SYM 1
#define SEQUENCER_MEM_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define SEQUENCER_MEM_MEMORY_INFO_MEM_INIT_FILENAME dut_dut_e0_if0_p0_s0_sequencer_mem


#endif /* _ALTERA_SEQUENCER_MEM_BRIDGE_INST_H_ */
